version: '3.9'

volumes:
  # Store VS Code extensions in named volume to prevent re-downloads.
  # See: https://code.visualstudio.com/remote/advancedcontainers/avoid-extension-reinstalls
  # Also see: https://github.com/microsoft/vscode-remote-release/issues/7690
  vscode-extensions:
  # Store pip wheel cache in named volume to prevent re-downloads.
  pip-whl-cache:

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev

    volumes:
      # Store VS Code extensions in named volume to prevent re-downloads.
      - vscode-extensions:/root/.vscode-server
      # Store pip wheel cache in named volume to prevent re-downloads.
      - pip-whl-cache:/root/.cache/pip
      # Allow access to Docker daemon for VS Code Docker extension to work inside container.
      - /var/run/docker.sock:/var/run/docker.sock
      # (OPTION) Mount point for `data` folder.
      # - $USERPROFILE\Documents\project-name-data:/data:cached # $USERPROFILE (Windows) & $HOME (Linux) are absolute paths too.
      # (OPTION) Legacy support for mounting repository from host filesystem.
      # - .:/code:cached
      - ./rob_ws:$HOME/rob_ws

    # Better process handling by using a process management system (tini).
    init: true
    # Larger shared memory for VNC & ROS.
    shm_size: 1gb

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Used to allow ROS to communicate across containers.
    ipc: service:donor
    pid: service:donor

    # Isolate ROS nodes into their own network.
    network_mode: service:donor

    # Override default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

    # Request for GPU access.
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  # Example of setup for ROS to be able to communicate across containers.
  # Is unnecessary if using a single container.
  donor:
    ports:
      # Expose noVNC web app.
      - 6080:6080
      # Expose rosbridge.
      - 9090:9090

    # Used to allow ROS to communicate across containers.
    ipc: shareable
    pid: shareable

    image: alpine # smallest image
    stop_signal: SIGKILL
    command: sleep infinity
